baseURL: https://www.fountaincitykc.org/
title: "Fountain City Church - Overland Park, KS"
timeZone: America/Chicago
disableKinds: [RSS, taxonomy, term]
buildFuture: true # Needed to show future events
