goldmark:
  parser:
    attribute: # Enable Markdown attributes for block-level elements
      block: true
      title: true
    wrapStandAloneImageWithinParagraph: false # Do not wrap standalone images with paragraph tag
