main:
  - name: About Us
    pageRef: /vision/
    weight: 1
  - name: Vision
    pageRef: /vision/
    parent: About Us
    weight: 2
  - name: Our Staff
    pageRef: /staff/
    parent: About Us
    weight: 3
  - name: What We Believe
    pageRef: /what-we-believe/
    parent: About Us
    weight: 4
  - name: Children's and Family Ministry
    pageRef: /childrens-and-family-ministry/
    parent: About Us
    weight: 5
  - name: Visit
    pageRef: /sunday-morning/
    weight: 6
  - name: Sunday Morning
    pageRef: /sunday-morning/
    parent: Visit
    weight: 7
  - name: Kids' Classes
    pageRef: /kids-classes/
    parent: Visit
    weight: 8
  - name: Events
    pageRef: /events/
    weight: 9
  - name: Connect
    pageRef: /connect/
    weight: 10
  - name: Give
    params:
      rel: external
    url: https://fountaincitykc.churchcenter.com/giving
    weight: 11
