main:
  - name: About us
    pageRef: /vision/
    weight: 1
  - name: Vision
    pageRef: /vision/
    parent: About us
    weight: 2
  - name: Our staff
    pageRef: /staff/
    parent: About us
    weight: 3
  - name: What we believe
    pageRef: /what-we-believe/
    parent: About us
    weight: 4
  - name: Sunday morning
    pageRef: /sunday-morning/
    weight: 5
  - name: Events
    pageRef: /events/
    weight: 6
  - name: Connect
    pageRef: /connect/
    weight: 7
  - name: Give
    params:
      rel: external
    url: https://fountaincitykc.churchcenter.com/giving
    weight: 8
