media:
  input: static/media
  output: /media
content:
# Home Page
  - name: home
    label: Home
    type: file
    format: yaml-frontmatter
    path: content/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: params
        label: Params
        type: object
        fields:
          - name: banner
            label: Banner
            type: object
            fields:
              - name: enabled
                label: Enabled
                type: boolean
              - name: content
                label: Content
                type: rich-text
              - name: button
                label: Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                  - name: href
                    label: Button Link
                    type: string
          - name: hero
            label: Hero
            type: object
            fields:
              - name: video
                label: Video
                type: file
                multiple: false
                path: home
                required: true
              - name: poster
                label: Poster Image
                type: image
                options:
                  multiple: false
                  path: home
                required: true
              - name: logo
                label: Logo
                type: image
                options:
                  multiple: false
                  path: home
                required: true
              - name: headline
                label: Headline
                type: text
                required: true
              - name: subhead
                label: Subhead
                type: string
                required: true
              - name: button
                label: Watch Live Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                    required: true
                  - name: href
                    label: Button Link
                    type: string
                    required: true
          - name: callout
            label: Callout
            type: object
            fields:
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: link
                label: Link
                type: object
                fields:
                  - name: text
                    label: Link Text
                    type: string
                    required: true
                  - name: href
                    label: Link URL
                    type: string
                    required: true
          - name: cards
            label: Cards
            type: object
            list: true
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: home
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: button
                label: Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                  - name: href
                    label: Button Link
                    type: string
          - name: sermon
            label: Sermon
            type: object
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: home
                required: true
              - name: watch
                label: Watch
                type: object
                fields:
                  - name: text
                    label: Watch Text
                    type: string
              - name: listen
                label: Listen
                type: object
                fields:
                  - name: text
                    label: Listen Text
                    type: string
                  - name: href
                    label: Listen Link
                    type: string
          - name: events
            label: Events
            type: object
            fields:
              - name: headline
                label: Headline
                type: object
                fields:
                  - name: single
                    label: Single Event
                    type: string
                    required: true
                  - name: multiple
                    label: Multiple Events
                    type: string
                    required: true
              - name: button
                label: View All Events Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                    required: true
                  - name: href
                    label: Button Link
                    type: string
                    required: true
  # Vision
  - name: vision
    label: Vision
    type: file
    format: yaml-frontmatter
    path: content/vision/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Content
        type: rich-text
        required: true
  # Staff
  - name: staff
    label: Our Staff
    type: file
    format: yaml-frontmatter
    path: content/staff/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: params
        label: Params
        type: object
        fields:
          - name: sections
            label: Staff Members
            type: object
            list: true
            fields:
              - name: name
                label: Name
                type: string
                required: true
              - name: role
                label: Role
                type: string
              - name: email
                label: Email
                type: string
              - name: content
                label: Bio
                type: rich-text
                required: true
              - name: image
                label: Photo
                type: image
                options:
                  multiple: false
                  path: staff
                required: true
  # What We Believe
  - name: what-we-believe
    label: What We Believe
    type: file
    format: yaml-frontmatter
    path: content/what-we-believe/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: body
        label: Content
        type: rich-text
        required: true
  # Children's and Family Ministry
  - name: childrens-and-family-ministry
    label: Children's and Family Ministry
    type: file
    format: yaml-frontmatter
    path: content/childrens-and-family-ministry/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: keywords
        label: Keywords
        type: string
        list: true
        hidden: true
      - name: body
        label: Content
        type: rich-text
        required: true
  # Sunday Morning
  - name: sunday-morning
    label: Sunday Morning
    type: file
    format: yaml-frontmatter
    path: content/sunday-morning/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: params
        label: Params
        type: object
        fields:
          - name: sections
            label: Sections
            type: object
            list: true
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: sunday-morning
                required: true
              - name: button
                label: Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                    required: true
                  - name: href
                    label: Button Link
                    type: string
                    required: true
          - name: location
            label: Location
            type: object
            fields:
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: sunday-morning
                required: true
              - name: headline
                label: Headline
                type: string
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
          - name: directions
            label: Directions
            type: object
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
  # Kids Classes
  - name: kids-classes
    label: Kids' Classes
    type: file
    format: yaml-frontmatter
    path: content/kids-classes/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: keywords
        label: Keywords
        type: string
        list: true
        hidden: true
      - name: params
        label: Params
        type: object
        fields:
          - name: sections
            label: Sections
            type: object
            list: true
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: kids-classes
                required: true
  # Connect
  - name: connect
    label: Connect
    type: file
    format: yaml-frontmatter
    path: content/connect/_index.md
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
      - name: params
        label: Params
        type: object
        fields:
          - name: sections
            label: Sections
            type: object
            list: true
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: image
                label: Image
                type: image
                options:
                  multiple: false
                  path: connect
                required: true
              - name: tag
                label: Tag
                type: string
          - name: callout
            label: Callout
            type: object
            fields:
              - name: headline
                label: Headline
                type: string
                required: true
              - name: content
                label: Content
                type: rich-text
                required: true
              - name: button
                label: Button
                type: object
                fields:
                  - name: text
                    label: Button Text
                    type: string
                    required: true
  # Site Settings
  - name: site-settings
    label: Site Settings
    type: file
    format: yaml
    path: config/_default/params.yaml
    fields:
      - name: description
        label: Site Description
        type: text
        required: true
      - name: logos
        label: Logos
        type: object
        fields:
          - name: main
            label: Fountain City Church Logo
            type: image
            options:
              multiple: false
              path: logos
            required: true
          - name: kids
            label: FCC Kids & Families Logo
            type: image
            options:
              multiple: false
              path: logos
            required: true
      - name: contact
        label: Contact
        type: object
        fields:
          - name: email
            label: Email
            type: string
            required: true
          - name: phone
            label: Phone
            type: string
            required: true
      - name: serviceAddress
        label: Service Address
        type: object
        fields:
          - name: text
            label: Service Label
            type: string
            required: true
          - name: address
            label: Service Address
            type: string
            required: true
      - name: mailingAddress
        label: Mailing Address
        type: object
        fields:
          - name: text
            label: Mailing Label
            type: string
            required: true
          - name: address
            label: Mailing Address
            type: string
            required: true
      - name: directions
        label: Directions
        type: object
        fields:
          - name: text
            label: Directions Label
            type: string
            required: true
          - name: href
            label: Directions Link
            type: string
            required: true
      - name: connect
        label: Connect Section
        type: object
        fields:
          - name: headline
            label: Headline
            type: string
            required: true
          - name: content
            label: Content
            type: rich-text
            required: true
          - name: button
            label: Button
            type: object
            fields:
              - name: text
                label: Button Text
                type: string
                required: true
              - name: href
                label: Button Link
                type: string
                required: true
      - name: apps
        label: Apps Section
        type: object
        fields:
          - name: headline
            label: Headline
            type: string
            required: true
          - name: content
            label: Content
            type: rich-text
            required: true
          - name: buttons
            label: App Buttons
            type: object
            list: true
            fields:
              - name: text
                label: Button Text
                type: string
                required: true
              - name: href
                label: Button Link
                type: string
                required: true
              - name: image
                label: Button Image
                type: image
                options:
                  multiple: false
                  path: apps
                required: true
      - name: social
        label: Social Links
        type: object
        list: true
        fields:
          - name: text
            label: Social Platform
            type: string
            required: true
          - name: href
            label: Social Link
            type: string
            required: true
          - name: image
            label: Social Icon
            type: image
            options:
              multiple: false
              path: social
            required: true
      - name: events
        label: Events
        type: object
        fields:
          - name: defaultImage
            label: Default Event Image
            type: image
            options:
              multiple: false
              path: events
            required: true
