---
baseURL: "https://www.fountaincitykc.org/"
title: "Fountain City Church - Overland Park, KS"
timeZone: America/Chicago
disableKinds: ["RSS","taxonomy","term"]
menu:
  main:
  - name: About us
    pageRef: /about-us/
    weight: 1
  - name: Mission & vision
    pageRef: /about-us/
    parent: About us
    weight: 2
  - name: Our staff
    pageRef: /staff/
    parent: About us
    weight: 3
  - name: What we believe
    pageRef: /what-we-believe/
    parent: About us
    weight: 4
  - name: Sunday morning
    pageRef: /sunday-morning/
    weight: 5
  #- name: Events
  #  pageRef: /events/
  #  weight: 6
  - name: Connect
    pageRef: /connect/
    weight: 7
  - name: Give
    params:
      rel: external
    url: https://fountaincitykc.churchcenter.com/giving
    weight: 8
params:
  address: "9101 Nall Ave, Prairie Village, KS 66207"
  mailingAddress: "11605 Foster St, Overland Park, KS 66210"
  email: james@fountaincitykc.org
  phone: 303-618-3079
...
