backend:
  name: github
  repo: fountaincitykc/fountaincitykc.github.io
  branch: master
  site_domain: fountaincitykc.org
  commit_messages:
    create: 'Create {{collection}} "{{slug}}"'
    update: 'Update {{collection}} "{{slug}}"'
    delete: 'Delete {{collection}} "{{slug}}"'
    uploadMedia: '[skip ci] Upload "{{path}}"'
    deleteMedia: '[skip ci] Delete "{{path}}"'

media_folder: "static/images"
public_folder: "/images"

site_url: https://fountaincitykc.org
display_url: https://fountaincitykc.org
logo_url: https://fountaincitykc.org/images/fountain-city-church-logo.svg

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        name: "home"
        label: "Home"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Banner"
                name: "banner"
                widget: "object"
                fields:
                  - {label: "Enabled", name: "enabled", widget: "boolean", default: false}
                  - {label: "Content", name: "content", widget: "markdown", required: false}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    required: false
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Hero"
                name: "hero"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "text"}
                  - {label: "Subhead", name: "subhead", widget: "string"}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Photos"
                name: "photos"
                widget: "object"
                fields:
                  - {label: "Main Photo", name: "photo0", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 1", name: "photo1", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 2", name: "photo2", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 3", name: "photo3", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 4", name: "photo4", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 5", name: "photo5", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Photo 6", name: "photo6", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
              - label: "Callout"
                name: "callout"
                widget: "object"
                fields:
                  - {label: "Content", name: "content", widget: "text"}
                  - label: "Link"
                    name: "link"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Cards"
                name: "cards"
                widget: "list"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Latest Sermon"
                name: "sermon"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/home", public_folder: "/home"}
                  - label: "Watch Button"
                    name: "watch"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string", required: false}
                  - label: "Listen Button"
                    name: "listen"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Featured Events"
                name: "events"
                widget: "object"
                fields:
                  - label: "Headline"
                    name: "headline"
                    widget: "object"
                    fields:
                      - {label: "Single", name: "single", widget: "string"}
                      - {label: "Multiple", name: "multiple", widget: "string"}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}

      - file: "content/vision/_index.md"
        name: "vision"
        label: "Vision"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}

      - file: "content/staff/_index.md"
        name: "staff"
        label: "Staff"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Staff Members"
                name: "staff"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string"}
                  - {label: "Role", name: "role", widget: "string"}
                  - {label: "Email", name: "email", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/staff", public_folder: "/staff"}

      - file: "content/what-we-believe/_index.md"
        name: "what-we-believe"
        label: "What We Believe"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}

      - file: "content/childrens-and-family-ministry/_index.md"
        name: "childrens-and-family-ministry"
        label: "Children's and Family Ministry"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - {label: "Content", name: "body", widget: "markdown"}

      - file: "content/sunday-morning/_index.md"
        name: "sunday-morning"
        label: "Sunday Morning"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Sections"
                name: "sections"
                widget: "list"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/sunday-morning", public_folder: "/sunday-morning"}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    required: false
                    fields:
                      - {label: "Text", name: "text", widget: "string"}
                      - {label: "Link", name: "href", widget: "string"}
              - label: "Location"
                name: "location"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/sunday-morning", public_folder: "/sunday-morning"}
              - label: "Directions"
                name: "directions"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}

      - file: "content/kids-classes/_index.md"
        name: "kids-classes"
        label: "Kids Classes"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Sections"
                name: "sections"
                widget: "list"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/kids-classes", public_folder: "/kids-classes"}

      - file: "content/connect/_index.md"
        name: "connect"
        label: "Connect"
        format: "frontmatter"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text", required: false}
          - label: "Parameters"
            name: "params"
            widget: "object"
            fields:
              - label: "Sections"
                name: "sections"
                widget: "list"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - {label: "Photo", name: "photo", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/connect", public_folder: "/connect"}
                  - {label: "Tag", name: "tag", widget: "string", required: false, hint: "Used to link to all events with this tag"}
              - label: "Callout"
                name: "callout"
                widget: "object"
                fields:
                  - {label: "Headline", name: "headline", widget: "string"}
                  - {label: "Content", name: "content", widget: "markdown"}
                  - label: "Button"
                    name: "button"
                    widget: "object"
                    fields:
                      - {label: "Text", name: "text", widget: "string"}

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Tags", name: "tags", widget: "list", default: []}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - label: "Parameters"
        name: "params"
        widget: "object"
        fields:
          - {label: "Featured", name: "featured", widget: "boolean", default: false}
          - {label: "Featured Image", name: "image", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/content/events", public_folder: "/events", required: false}
          - {label: "Time", name: "time", widget: "string", required: false}
          - {label: "Location", name: "location", widget: "string", required: false, hint: "Can include markdown links"}
          - label: "Button"
            name: "button"
            widget: "object"
            required: false
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "href", widget: "string"}

  - name: "sermons"
    label: "Sermons"
    folder: "content/sermons"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - label: "Parameters"
        name: "params"
        widget: "object"
        fields:
          - {label: "Series", name: "series", widget: "relation", collection: "series", value_field: "title", search_fields: ["title"], required: false}
          - {label: "YouTube ID", name: "youtubeId", widget: "string", required: false, hint: "The ID from the YouTube video URL (e.g., '0tTNH7CE6dM' from 'https://www.youtube.com/watch?v=0tTNH7CE6dM')"}

  - name: "series"
    label: "Sermon Series"
    folder: "content/series"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "config"
    label: "Configuration"
    files:

      - file: "config/_default/params.yaml"
        label: "Parameters"
        name: "params"
        fields:
          - {label: "Site Description", name: "description", widget: "text"}
          - {label: "OpenGraph Images", name: "images", widget: "list", required: false}
          - label: "Contact Information"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Phone", name: "phone", widget: "string"}
          - label: "Service Address"
            name: "serviceAddress"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
          - label: "Mailing Address"
            name: "mailingAddress"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Address", name: "address", widget: "string"}
          - label: "Directions"
            name: "directions"
            widget: "object"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "href", widget: "string"}
          - label: "Connect"
            name: "connect"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Content", name: "content", widget: "text"}
              - label: "Button"
                name: "button"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "href", widget: "string"}
          - label: "Apps"
            name: "apps"
            widget: "object"
            fields:
              - {label: "Headline", name: "headline", widget: "string"}
              - {label: "Content", name: "content", widget: "text"}
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "Link", name: "href", widget: "string"}
                  - {label: "Image", name: "image", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/assets/apps", public_folder: "/apps"}
          - label: "Social"
            name: "social"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Link", name: "href", widget: "string"}
              - {label: "Icon", name: "icon", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/assets/icons", public_folder: "/icons"}
          - label: "Events"
            name: "events"
            widget: "object"
            fields:
              - {label: "Default Image", name: "defaultImage", widget: "image", choose_url: false, allow_multiple: false, media_folder: "/assets/events", public_folder: "/events"}
